name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open app
        2. Do something
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: false

  - type: dropdown
    id: macos
    attributes:
      label: macOS Version
      options:
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - Other
    validations:
      required: true

  - type: dropdown
    id: chip
    attributes:
      label: Mac Chip
      options:
        - Apple Silicon (M1/M2/M3/M4)
        - Intel
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MagicTouch Version
      placeholder: v1.0.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste logs from `/tmp/magictouch_debug.log` if available"
      render: shell
    validations:
      required: false

