name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for your suggestion!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see?
      placeholder: Describe your idea...
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Why do you need this feature?
      placeholder: I want this because...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any workarounds you've tried?
    validations:
      required: false

